models:
    sgan5: &sgan5
        model_type: 'SGAN'
        ngf: 64
        ndf: 64
        nz: 50 # depth of the latent z tensor
        npx: 129 # num of pixels width/height of images in X
        nw: 5 # height and width of z tensor
    psgan5: &psgan5
        model_type: 'PSGAN'
        ngf: 64
        ndf: 64
        nz: 64
        nh: 60
        nz_local: 20
        nz_global: 40
        nz_period: 4
        npx: 129
        nw: 5

default: &default_params
    workers: 2 # number of data loading workers
    batchSize: 64 # input batch size
    imageSize: 516 # the height / width of the input image to network
    ntw: 160 # height and width of z tensor at test time
    niter: 25 # number of epochs to train for
    lr: 0.0002 # learning rate
    beta1: 0.5 # beta1 for adam
    cuda: True # enables use_cuda
    ngpu: 1 # number of GPUs to use
    netG: '' # path to netG (to continue training)
    netD: '' # path to netD (to continue training)
    outf: 'outputs/' # folder to output images and model checkpoints
    manualSeed: # manual seed
    n_sample: 10 # number of samples for each image
    models: *sgan5

archpc:
    <<: *default_params
    imageSize: 600
    ntw: 40
    n_sample: 480
    batchSize: 24
    lr: 0.0002
    niter: 200
    model: *psgan5
